name: 上传到七牛存储
on: push


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hujiulong/action-qiniu-upload@master
      with:
        # Your qiniu access key, required.
        access_key: ${{ secrets.AK }}

        # Your qiniu secret key, required.
        secret_key: ${{ secrets.SK }}

        # Bucket name, required.
        bucket: editors
